server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  config:
    import: optional:file:.env.properties
  application:
    name: ${APP_NAME:pretor-sport-backend}

  datasource:
    url: jdbc:postgresql://localhost:5432/pretor_sport_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true  #cambiar a true temporalmente para debuggear
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    time-zone: America/Mexico_City

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:admin}
      password: ${SPRING_SECURITY_USER_PASSWORD:admin123}
      roles: ADMIN

#configuración específica de la aplicación
app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:4200}
  jwt:
    secret: ${JWT_SECRET:pretorSportSecretKeyForJWTTokenGenerationThatShouldBeLongEnoughForHS512Algorithm}
    expiration: ${JWT_EXPIRATION:86400} # 24 horas en segundos
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800} # 7 días en segundos
  ecommerce:
    currency: MXN
    tax-rate: 0.16
    shipping:
      standard: 
        cost: 99.00
        days: 5-7
      express:
        cost: 199.00
        days: 2-3
      premium:
        cost: 299.00
        days: 1
    inventory:
      low-stock-threshold: 5
      out-of-stock-threshold: 0
  images:
    base-url: http://localhost:8080/images
    upload-dir: uploads/images
    allowed-extensions: jpg,jpeg,png,gif,webp
    max-size: 5MB

#configuración de logging
logging:
  level:
    com.pretor_sport.app: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.boot.context.config: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/pretor-sport.log

#configuración de validacion
validation:
  messages:
    locale: es_MX

#configuración de paginacion por defecto
pagination:
  default-page-size: 20
  max-page-size: 100

#configuración de cache
cache:
  categories:
    ttl: 3600 # 1 hora
  products:
    ttl: 1800 # 30 minutos
